apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demo1201aks-866a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demo1201aks-866a"
  template:
    metadata:
      labels:
        app: "demo1201aks-866a"
    spec:
      containers:
        - name: "demo1201aks-866a"
          image: "demo1201acr.azurecr.io/demo1201aks"
          ports:
          - containerPort: 80