apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
        - name: simpleweb
          image: ghcr.io/lettucebo/demo1201
          ports:
            - containerPort: 80
