on:   
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demo1201acr.azurecr.io
        username: ${{ secrets.acr_demo1201acr_username }}
        password: ${{ secrets.acr_demo1201acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/src/SimpleWeb" -f  "src/SimpleWeb/Dockerfile" -t demo1201acr.azurecr.io/demo1201aks:${{ github.sha }} --label dockerfile-path=src/SimpleWeb/Dockerfile
        docker push demo1201acr.azurecr.io/demo1201aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demo1201aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo1201aks9a26 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo1201aks9a26`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo1201aks9a26
        container-registry-url: demo1201acr.azurecr.io
        container-registry-username: ${{ secrets.acr_demo1201acr_username }}
        container-registry-password: ${{ secrets.acr_demo1201acr_password }}
        secret-name: demo1201aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demo1201aks9a26
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          demo1201acr.azurecr.io/demo1201aks:${{ github.sha }}
        imagepullsecrets: |
          demo1201aksdockerauth
